### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by morenoh149** [aerupt/whenareyou#10]
I get this error on kaggle
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-15-f1891c8d087c> in <module>
----> 1 tz = whenareyou('Madrid')
      2 tz

/opt/conda/lib/python3.6/site-packages/whenareyou/__init__.py in whenareyou(address)
     50     latlong = cached_json_get(
     51         LONG_LAT_URL.format(quote_plus(address))
---> 52     )['results'][0]['geometry']['location']
     53 
     54     return get_tz(latlong['lat'], latlong['lng'])

IndexError: list index out of range
```

**Comment by fili** [comment]
Same here:

```
>>> tz = whenareyou('Hamburg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/whenareyou/__init__.py", line 52, in whenareyou
    )['results'][0]['geometry']['location']
IndexError: list index out of range
```

**Comment by sils** [comment]
I think the google API needs authentication by now which this library does not support. See also #6 however as of today that's not ready to be merged but may help you.
